### PR TITLE
Add version string

### LINKED ISSUE #10: No version string
Now that desietc is now part of the standard DESI release, it needs to be brought up to standard.  For starters, there is no version string:
```python
import desietc.__version__ as desietc_version
```
won't work.

### PR DESCRIPTION
**Pull request by weaverba137**
This PR closes #10.

Note that [PEP 440](https://peps.python.org/pep-0440/) specifies `X.Y.Z.dev`, not `X.Y.Zdev`.

### CODE REVIEW

**Comment by weaverba137** [comment]
@dkirkby, @schlafly, I think this PR is not controversial, so I will self-merge unless I hear from you by 1 December.

**Comment by schlafly** [comment]
This looks fine to me, but you really need dkirkby.

**Comment by dkirkby** [comment]
Also fine with me, thanks @weaverba137

**Comment by weaverba137** [comment]
Thank you!

**Pull request merged**
